version: '3.8'
name: nebula

services:
  nebula-postgres:
    image: 'postgres:16'
    container_name: nebula-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - PGUSER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    networks:
      - nebulaNet

filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:9090"
    volumes:
      - /home/bibburat/Share/:/srv
      - /home/bibburat/Infrastructure/filebrowser/data/:/database
      - /home/bibburat/Infrastructure/filebrowser/config/:/config
    environment:
      - PUID=1000  # ID пользователя (можно узнать командой 'id')
      - PGID=1000  # ID группы
      - TZ=Asia/Yekaterinburg 

networks:
  nebulaNet:
    name: nebulaNet
    driver: bridge

    
volumes:
  postgres_data: